// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_500_champion = "CgkI7oXMgOgUEAIQAg"; // <GPGSID>
        public const string achievement_you_liked_my_game = "CgkI7oXMgOgUEAIQEg"; // <GPGSID>
        public const string achievement_give_me_more = "CgkI7oXMgOgUEAIQDQ"; // <GPGSID>
        public const string achievement_you_almost_have_them = "CgkI7oXMgOgUEAIQEA"; // <GPGSID>
        public const string achievement_welcome = "CgkI7oXMgOgUEAIQAA"; // <GPGSID>
        public const string achievement_boom = "CgkI7oXMgOgUEAIQCg"; // <GPGSID>
        public const string achievement_go_ahead_with_all = "CgkI7oXMgOgUEAIQAQ"; // <GPGSID>
        public const string achievement_2_birds = "CgkI7oXMgOgUEAIQCw"; // <GPGSID>
        public const string achievement_agility_mastery = "CgkI7oXMgOgUEAIQDA"; // <GPGSID>
        public const string achievement_vanilla_loaded_ice_cream = "CgkI7oXMgOgUEAIQBw"; // <GPGSID>
        public const string achievement_collector = "CgkI7oXMgOgUEAIQCA"; // <GPGSID>
        public const string achievement_10000_champion = "CgkI7oXMgOgUEAIQBA"; // <GPGSID>
        public const string achievement_break_ships = "CgkI7oXMgOgUEAIQBQ"; // <GPGSID>
        public const string achievement_you_liked_my_game_a_lot = "CgkI7oXMgOgUEAIQEw"; // <GPGSID>
        public const string achievement_breaking_the_space = "CgkI7oXMgOgUEAIQCQ"; // <GPGSID>
        public const string achievement_ship_champion = "CgkI7oXMgOgUEAIQBg"; // <GPGSID>
        public const string achievement_a_whole_machine = "CgkI7oXMgOgUEAIQEQ"; // <GPGSID>
        public const string achievement_i_came_looking_for_copper = "CgkI7oXMgOgUEAIQDg"; // <GPGSID>
        public const string achievement_5000_champion = "CgkI7oXMgOgUEAIQAw"; // <GPGSID>
        public const string achievement_your_first_category = "CgkI7oXMgOgUEAIQDw"; // <GPGSID>

}

